import Head from 'next/head'

import Header from "../components/Header"
import Navbar from "../components/Navbar"


import Main from "../components/Main"
import About from "../components/About"

import Contact from "../components/Contact"

export default function Home() {
  return (

    
    <div>
      <Head>
        <title>Ramon's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <About />
      <Contact />
      
      
      
    </div>
    
  )
}
